language: objective-c
osx_image: xcode8.3
script:
    - xcodebuild clean build test -sdk iphonesimulator -project CodingTextView.xcodeproj -scheme CodingTextViewTests -destination 'platform=iOS Simulator,name=iPhone 7'